### ISSUE TITLE
Issue - /give/ - Donate link only gives Direct Debit option (no individual gift option) 

### ISSUE THREAD

**Issue by jstricklin-coutinho** [TheRestartProject/therestartproject.org#1]
On http://therestartproject.org/give/, the choice of gift (Monthly or Just Once) does not carry through to the JustGiving page referred to on the ensuing JustGiving form (only offers the option of giving monthly).  The amount of money chosen (e.g. £25) does carry through.

**Comment by ngm** [comment]
@ugomatic mentioned that the link from our site to JustGiving is hardcoded in one of the pages - probably in the Restart theme - I'll take a look into this.

**Comment by IronRunes** [comment]
@ngm the contents of the page is in the body of the wordpress page itself (it isn't hardcoded in the theme files). 
The wiring to JustGiving seems to be interrupted now (at least from Italy).

**Comment by jstricklin-coutinho** [comment]
The link to the "give monthly" seems alright, however the Give Once will need to point to the new part of Just Giving: https://donate.justgiving.com/donation-amount?uri=aHR0cHM6Ly9kb25hdGUtYXBpLmp1c3RnaXZpbmcuY29tL2FwaS9kb25hdGlvbnMvZTg3M2U2MWJiMTExNDRlNTliMmE3ZjI2YTVhMjg3ZjE=

**Comment by ngm** [comment]
The donation section has been replaced with a direct link to JustGiving for now, where both one-off and monthly donations can be made.  We'll be replacing JustGiving with a different provider in June, at which point we'll (hopefully) reinstate the one-off and direct payment buttons to our own page.
