### ISSUE TITLE
Error loading data in /groups page

### ISSUE THREAD

**Issue by ugomatic** [TheRestartProject/therestartproject.org#100]
When loading /groups, the Fixometer data from one (or at times two) groups doesn't load, showing the following error message. The group affected keeps changing

![group-page-loading-error](https://user-images.githubusercontent.com/4210589/30023733-901b321c-9168-11e7-8ca2-056dc6b12517.png)

**Comment by ngm** [comment]
Just noting that I have't seen this issue come up - is it continuing to occur for you @ugomatic ?

**Comment by ugomatic** [comment]
This hasn't occurred recently - will keep an eye on it and report if it happens again

**Comment by ngm** [comment]
Most reports of this error that I see make mention of memcached, which we have not set up.  It's possible (but unlikely) that Vidahost have this set up.

One possible I've seen is setting memcached.sess_lock_expire in php.ini, but unless the issue reoccurs it will not make sense to change this for us.

> Probably caused by php-memcached-dev/php-memcached#266; workaround is to explicitly set memcached.sess_lock_expire (with the same value as max_execution_time being a sane default).
-- https://github.com/magento/magento2/issues/5319#issuecomment-275842714

@ugomatic I will this for now but please reopen if the issue reoccurs.
