### ISSUE TITLE
404 when clicking "Next" on category page

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/therestartproject.org#113]
This happened to me when clicking "next" on /education

**Comment by ngm** [comment]
This is happening for all categories.  Not sure what is causing this.  

Apparently it used to happen and was fixed.  

Possible recent changes that could have affected it:

* Wordpress upgrade.  Last pull Wordpress update was to version 4.9.4 on Feb 9th.  
* SEO changes to category pages.  SEO changes were made around Feb 23rd/26th.  I don't think anything would have caused this, but it's a recent change.
* Yoast plugin update.  I have seen yoast play around with category URLs before.

My local dev installation is from Feb 27th, and it is working fine there.

**Comment by ngm** [comment]
Debug This shows that for page 2 of a category, the following rewrite rule is being matched:

> Matched Query: category_name=education&name=page&page=2

The `name=page` bit looks incorrect.

**Comment by ngm** [comment]
Pagination is working fine for the /blog/ pages, e.g. /blog/page/2 works fine.  The rewrite rule that is matched is:

> Matched Query: pagename=blog&paged=2

**Comment by ngm** [comment]
Appears to be the classic problem of Wordpress seeing the page section of the url as the name of the post when permalinks are set up as /%category%/%postname%/.

Fixed with:

```
function remove_page_from_query_string($query_string) {                                        
        if (is_admin()) return $query_string;                                                    
        if ($query_string['name'] == 'page' && isset($query_string['page'])) {                   
                unset($query_string['name']);                                                 
                $query_string['paged'] = $query_string['page'];                      
        }                                                                                      
        return $query_string;                                                      
}                                                                                              
add_filter('request', 'remove_page_from_query_string');    
```

in functions.php, although I'm bamboozled as to why this issue suddenly appeared.  The only thing with any slight relation is the changelog for Yoast v7.1:

> * Fixes a bug where the page and paged values could cause errors if they weren’t properly handled as integers.

but I installed the latest version of Yoast and it didn't make any difference.
