### ISSUE TITLE
Alternate link (RSS) is broken

### ISSUE THREAD

**Issue by acrostich** [TheRestartProject/therestartproject.org#124]
The link in this alternate tag on the homepage is broken:

`<link rel="alternate" type="application/rss+xml" title="The Restart Project &raquo; Homepage Comments Feed" href="https://therestartproject.org/homepage/feed/" />`

I haven't checked on the other pages.

**Comment by acrostich** [comment]
The feeds appear in the feed icon extension I have for Safari, but clicking on them does not load any feed. I suppose this may be due to the login requirements.

I can load both in the Vienna RSS reader, however:
* the main one has only old entries from last year (is this because it is on the staging server?)
* the formatting of the entries for the podcast seems wrong with each post starting with entries such as 
`[soundcloud url=”https://api.soundcloud.com/tracks/313859005″ params=”color=ff5500&inverse=false&auto_play=false&show_user=true” width=”100%” height=”20″ iframe=”true” /]`

The feeds I'm currently using that work (apart from the recent issues with the podcast one) are:
https://therestartproject.org/feed/
https://therestartproject.org/feed/podcast/
So you may want to change http to https in you alternate tags

In the alternate tags I'd also delete ' - RSS 2.0 Feed' as this is not helpful.

I'd suggest you offer an RSS or an Atom feed, whichever is easier for you to deliver. As far as I know most/all aggregators can deal with both so it doesn't matter which format you choose.

In Vienna, the feeds got called:
'The Restart Project' and 'The Restart Podcast'. These must be the names included in the rss feeds. You should make sure they are the same one as the ones in the alternate tags which are better.

**Comment by ngm** [comment]
This changes should now be visible on the live site - please have a check when you get chance @acrostich.  Thanks for your help.

**Comment by ngm** [comment]
Thanks @acrostich. Oof, quite a few validation errors on the feed.  Although, it seems RSS readers are quite forgiving - I can import the feeds successfully in Feedly on my Android device and Liferea on Linux.

I'll put in a new issue for fixing the validation errors, and close this one.  Many thanks.
