### ISSUE TITLE
Speed issues

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/therestartproject.org#22]
Our site currently has poor page speed.  Slow pages negatively affect the user experience (and therefore potentially user conversions). Furthermore our site scores badly in Google PageSpeed, which will affect our SEO.  Page load is noticeably worse when logged in.  However it is still slow for general visitors to the site.

The two main parts of the page load time are server-side rendering (Wordpress putting the page together), and client-side rendering (the browser downloading and parsing the HTML/JS/CSS).  Around 75% of the page load is server-side rendering.  

Improving server-side rendering will have the biggest effect on page speed.  However improving the client-side rendering is just as important in order to improve the PageSpeed rating (and hence improve our SEO).

**Comment by IronRunes** [comment]
most likely connected to #23

**Comment by ngm** [comment]
Marking this as closed.  Still some outstanding issues, but majority has been resolved.  As far as user perception is concerned, speed is pretty good now (mostly thanks to caching.)

A couple of issues remaining with needing image optimization performed at upload time, but leaving this for now as we already have problems with image manipulation during upload (see #7).

Also kept jquery in the header as it caused issues on the /give and /code pages to have it in the footer.  Going to revisit this once the current fundraiser has completed, don't want to fiddle around with the JS on there any further right now.

Page load time is slightly improved, from about ~2 seconds to ~1.5 as reported by Google.  On staging we had it down to about 0.2ms so maybe it is the server?  It's decently specced though.  We're also up to the latest PHP version.  One last thing to try is running DB optimisations, I recall there being a ton of old crufty DB records when I was doing a backup at some point.  These wouldn't be included on staging so it's possible it's a culprit.
