### ISSUE TITLE
Calendar Embed

### ISSUE THREAD

**Issue by jstricklin-coutinho** [TheRestartProject/therestartproject.org#30]
The "Upcoming Events" calendar feed relies on the older, more disused GCal feed from therestartproject@gmail.com. This relies on manual input of each event in order to feed onto the front page.  

We will need to change this to an option which takes in feeds automatically - the Meetup London group offers an RSS calendar feed, however worldwide is needed.

**Comment by ngm** [comment]
Same as #24 ?

**Comment by jstricklin-coutinho** [comment]
Yes, we can close and merge this one with #24
