### ISSUE TITLE
Restart Code - flag that comments left when signing up will be displayed publicly

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/therestartproject.org#32]
When people sign up to the code, we should flag that comments left in the 'Leave a comment' box will be displayed on our website.

**Comment by janetgunter** [comment]
This appears to occur on Chrome as an "auto-complete" - it automatically entered my mobile number. Hope there is a way to disable this?

**Comment by ngm** [comment]
Set `autocomplete="off"` for the comment field.  Tested in Chrome, and it no longer autocompletes the comment field.  Have also updated placeholder text to let people know the comment will be public.
