### ISSUE TITLE
Email alerts of new blog posts no longer being sent out by Jetpack

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/therestartproject.org#34]
As reported by @ugomatic .

In @ugomatic 's personal list of Wordpress subscriptions, the link for the Restart Project subscription now points to therestartproject.dev (i.e. the URL for the dev setup on my local machine.)

Somehow the local version setup via Duplicator has overriden the Jetpack connection for the live site.

**Comment by janetgunter** [comment]
Also just noting that Jetpack's other features on the WP dashboard appear to be affected

**Comment by ngm** [comment]
Thread discussing this issue: https://wordpress.org/support/topic/how-to-have-a-clone-website-and-jetpack/

Non-production sites can be marked as staging for Jetpack: https://jetpack.com/support/staging-sites/

**Comment by ngm** [comment]
@ugomatic has raised an issue with Jetpack support.

**Comment by ngm** [comment]
This was resolved by Jetpack support.  They reassociated Jetpack to therestartproject.org behind the scenes.
