### ISSUE TITLE
dead links on website

### ISSUE THREAD

**Issue by timshand** [TheRestartProject/therestartproject.org#41]
[this page ](https://therestartproject.org/press/) has one dead link and one link that needs subscription to view

**Comment by ngm** [comment]
Thanks @timshand !  I've gone through and updated the broken/outdated links that I could find.  For the PC Pro link we'll see if we can get a PDF of the article up.

**Comment by ngm** [comment]
Hi @timshand - we're checking to see if we can post the article.

**Comment by ngm** [comment]
Links updated.
