### ISSUE TITLE
Add PayPal option to /give page

### ISSUE THREAD

**Issue by ugomatic** [TheRestartProject/therestartproject.org#52]
As a short-term solution, we should add a link to this page in the donation page:
https://www.paypal.com/uk/fundraiser/charity/61071

We need to adapt both copy and graphic, to highlight that if people donate with PayPal, we get 100% the donation

**Comment by ngm** [comment]
@ugomatic to confirm is this to replace or to be added in addition to the justgiving link?

**Comment by ugomatic** [comment]
This is in addition to Justgiving (as it requires paying with PayPal, which not everyone has or want to do) 

---- On Fri, 24 Mar 2017 10:54:48 +0000 notifications@github.com wrote ----

@ugomatic to confirm is this to replace or to be added in addition to the justgiving link?

**Comment by ngm** [comment]
@ugomatic please see wireframe below - something like this?  

The extra copy says: 'Please note: On donations made with Paypal, The Restart Project receives 100% of the donation.'  Any changes needed to that?


![image](https://cloud.githubusercontent.com/assets/172324/26362854/319d5450-3fd7-11e7-8639-c5056e20e241.png)

**Comment by ngm** [comment]
/give updated with PayPal button and extra copy.
