### ISSUE TITLE
Different link to subscribe to iTunes on podcast blog posts since December 8th

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/therestartproject.org#58]
Compare the iTunes subscribe links in  https://therestartproject.org/podcast/spindoctor/ vs https://therestartproject.org/podcast/spindoctor2/ .

In the former the iTunes subscribe link is: 
itpc://therestartproject.org/feed/podcast

on the latter it is:
https://therestartproject.org/feed/podcast

The former opens up iTunes if installed (although from a quick test doesn't seem to subscribe the user), the latter is the basic RSS feed link.

Needs some investigation as to what is the correct link for subscribing in iTunes - either the itpc one, or maybe something new.

**Comment by ngm** [comment]
As per #59, the itpc link is the correct link.

**Comment by ugomatic** [comment]
Lauren fixed all these links
