### ISSUE TITLE
Update itpc links on podcast episodes

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/therestartproject.org#99]
Reply from Blubrry: https://wordpress.org/support/topic/itpc-links-support/#post-9312677

Janet 18 days ago
So we need to change the "iTunes" link in podcast posts?

Neil Mather 17 days ago
I think we should, yes - from what Blubrry says it looks like it'll still work for the desktop iTunes, but yeah I think we should change to the one that is supported for iOS.

Ugo 17 days ago
I think we should test it with an iphone as that's the most likely user case

Neil Mather 17 days ago
So I think this is the direct link that we should use - https://itunes.apple.com/us/podcast/the-restart-podcast/id983603182?mt=2  (as found via here - https://linkmaker.itunes.apple.com/en-us/details/983603182?country=us&mediaType=podcasts&term=restart+radio)

Neil Mather 17 days ago
I don't see anywhere in Blubrry where we tell it where we are on iTunes, is that correct?  We put the links directly manually into each episode post?  (In which case I should be fine to update the plugin.)

**Comment by ugomatic** [comment]
Just to confirm Neil's point: Mozilla handles this in that way with their new IRL podcast: https://irlpodcast.org/ [linking directly to the url of the podcast on itunes]

**Comment by ngm** [comment]
The new restart_podcast WP shortcode includes the updated link for itunes.
So when we update old podcast posts to use the new shortcode, they will automatically include the new link.
